# Welcome to Serverless!



service: aws-lambda-crud

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-2
  iamRoleStatements: # Permisos de la tabla. Ya este proyecto puede acceder a TaskTable
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: # Que tabla voy a tener permisos de escribir
        - arn:aws:dynamodb:us-east-2:489292892831:table/TaskTable
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: 
        - arn:aws:dynamodb:us-east-2:489292892831:table/UserTable   

plugins:
  - serverless-offline


functions:
  hello:
    handler: src/handler.hello
  helloUser:
    handler: src/handler.helloUser  
    events:
      - httpApi:
          path: /user
          method: GET
  createTask:
    handler: src/addTask.addTask
    events:
      - httpApi:
          path: /tasks
          method: POST
  getTasks:
    handler: src/getTasks.getTasks
    events:
      - httpApi:
          path: /tasks
          method: GET   
  getOneTask:
    handler: src/getOneTask.getOneTask
    events:
      - httpApi:
          path: /tasks/{id}
          method: get  
  updateTask:
    handler: src/updateTask.updateTask
    events:
      - httpApi:
          path: /tasks/{id}
          method: put  
  deleteTask:
    handler: src/deleteTask.deleteTask
    events:
      - httpApi:
          path: /tasks/{id}
          method: delete  
  createUser:
    handler: src/user/createUser.createUser
    events:
      - httpApi:
          path: /v1/users
          method: POST  
  login:
    handler: src/user/login.login
    events:
      - httpApi:
          path: /v1/login                                       
          method: post                               

resources: 
  Resources:  
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TaskTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:  # Este es el primary key
          - AttributeName: id 
            AttributeType: S
        KeySchema:
          - AttributeName: id  
            KeyType: HASH
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UserTable
        BillingMode: PAY_PER_REQUEST          
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH        
    


        

